### ISSUE TITLE
Can we have a configure script to compile chan_respoke for 64-bit CENTOS?

### ISSUE THREAD

**Issue by justinvhester** [respoke/chan_respoke#10]
While installing chan_respoke on Centos 6.6 64-bit the respoke .so files were not moved to the /usr/lib64/asterisk/modules directory. Found the Makefile assumes the user lib directory for Asterisk is /usr/lib/asterisk.

`AST_MODULES_DIR=$(AST_EXECS_DIR)/lib/asterisk/modules`

Since this is hard coded so I can't fix it with something like 
`make AST_MODULES_DIR=/usr/lib64/asterisk/modules`

I resolved it in my lab by doing this in the chan_respoke source directory.
`find . -type f -name "*.so" -exec install -m 755 {} /usr/lib64/asterisk/modules \;`

Could we use a configure script (as with Asterisk) to let the Makefile know about the different directory name?

ie  `./configure --libdir=/usr/lib64`

**Comment by justinvhester** [comment]
Turns out I could fix it with something like `make VAR=/foo`.

Doing this
`make install AST_MODULES_DIR=/usr/lib64/asterisk/modules`
caused the modules to appear in the proper directory after a make clean and removing the respoke so files.

So a bit less painful than remodeling a line from the Makefile but still more fiddly than an option passed to a configure script.

**Comment by chadxz** [comment]
Hey Justin, we'd definitely accept a PR for that if you wanna send one. 

Regardless, thanks for reporting back what you did to get it to work.
