### ISSUE TITLE
doesn't build with Asterisk 14

### ISSUE THREAD

**Issue by chadxz** [respoke/chan_respoke#23]
```
In file included from res/res_respoke/respoke_endpoint.c:28:0:
res/res_respoke/respoke_endpoint.c: In function 'respoke_endpoint_initialize':
res/res_respoke/respoke_endpoint.c:720:2: error: 'AST_MODULE_SELF' undeclared (first use in this function)
  ast_cli_register_multiple(cli_respoke_endpoint, ARRAY_LEN(cli_respoke_endpoint));
  ^
res/res_respoke/respoke_endpoint.c:720:2: note: each undeclared identifier is reported only once for each function it appears in
Makefile:81: recipe for target 'res/res_respoke/respoke_endpoint.o' failed
make: *** [res/res_respoke/respoke_endpoint.o] Error 1
```

**Comment by chadxz** [comment]
@kharwell @jcolp any ideas?

**Comment by chadxz** [comment]
looks to be caused by this: https://issues.asterisk.org/jira/browse/ASTERISK-26278

**Comment by chadxz** [comment]
so i poked at it for a while but could never get it to fully work. On [my branch](https://github.com/respoke/chan_respoke/commit/0783b7611d28535a7a497014a8bbc7e2f3473bf8) I was able to get it to compile but would get "asterisk: symbol lookup error: /usr/lib/asterisk/modules/res_respoke.so: undefined symbol: __internal_respoke_transport_self" when i ran Asterisk.

I don't know what I'm doing so I'm sure it's just incredibly bad/wrong, but I tried... :/

**Comment by gtjoseph** [comment]
2 things you have to do...

Right before the AST_MODULE_INFO macro at the end of every module you need to add
```
#undef AST_BUILDOPT_SUM
#define AST_BUILDOPT_SUM ""
AST_MODULE_INFO(.....
```

In your Makefile you need to add a define for __internal_<module_name>_self to your compile recipe:
```
%.o: %.c
	$(COMPILE.c) -DAST_MODULE=\"$(notdir $(basename $@))\" -DAST_MODULE_SELF_SYM=__internal_$(notdir $(basename $@))_self $< -o $@

```
